services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8082:8081"
    depends_on:
      - mongo

  app:
    build: ./app
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: mongo
    depends_on:
      - mongo
